### ISSUE TITLE
Gladius "Create Node" not working

### ISSUE THREAD

**Issue by Lifeless-Ditto** [gladiusio/gladius-cli#10]
![capture](https://user-images.githubusercontent.com/33078150/38138876-8ecd23e4-345f-11e8-8527-1d4453a756f2.PNG)
For hours, i have been stuck at
"[Gladius-Node] Creating Node contract, please wait for tx to complete (this might take a couple of minutes)
[Gladius-Node] Transaction: undefined   [Pending]"

for longer than 8 hours. 

Probable questions:

1. Have i been accepted by the pool manager?
No

**Comment by kleoken** [comment]
You probably haven't run the right setup. Run `gladius-node init` to set your information and then run `gladius-node create` to create a node

**Comment by Lifeless-Ditto** [comment]
[Gladius-Node] Creating Node contract, please wait for tx to complete (this might take a couple of minutes)
{ Error: socket hang upion: undefined   [Pending]
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketOnEnd (_http_client.js:429:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
  code: 'ECONNRESET',
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.16.2' },
     method: 'get',
     url: 'http://localhost:3000/api/status/tx/undefined',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: 'localhost',
        port: '3000',
        path: '/api/status/tx/undefined',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/api/status/tx/undefined' },
     _redirectCount: 0,
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'GET /api/status/tx/undefined HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/status/tx/undefined',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://localhost:3000/api/status/tx/undefined' },
  response: undefined }

**Comment by kleoken** [comment]
Can you please describe your process up to this point. Starting with the first command you ran.

**Comment by Lifeless-Ditto** [comment]
To ensure that there was no outside factors, i restarted my whole rig. After that, i opened up 3 instances of cmd (all run with administrator permissions). After that, i ran gladius-node start (probably that's my error there). Then i ran gladius-node create. It asked for the standard stuff, which i had inputted. After which it showed me "Pending". I left it for a few hours, and when i came back i saw this screen.

**Comment by kleoken** [comment]
Do the restart again. Then run `gladius-node init` first and then `gladius-node create`. After that you can run `gladius-node apply` to apply to a pool and run `gladius-node start` to become an edge node if you are accepted by a pool

**Comment by Lifeless-Ditto** [comment]
This issue is solved. The application was successful. Interesting that it will not work if you did **gladius-node start** at first.

**Comment by kleoken** [comment]
`gladius-node init` is the first command you must run after installing
