### ISSUE TITLE
Separate generated configuration files and program code

### ISSUE THREAD

**Issue by sebastianhutter** [gladiusio/gladius-cli#16]
Currently the generated files (gpg keys and nodeFile.json) are stored together with the application code  in $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli:
- $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli/keys
- $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli/nodeFile.json

The directory and json file should be moved to a different path so we can easily replace the application code and also backup and secure the keys and nodeFile.json.

I propose to do this move in two steps, so we don't break the running beta installations:

**1. Step:**
Change the program code, so it looks for the keys and the nodeFile.json in $HOME/.gladius-cli

_The program is executed with `init` command:_

The `init` command will still create the files in $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli. Nothing changes here.

_The program is executed with any other command:_

1. Look for keys and nodeFile.json in $HOME/.gladius-cli. If valid files are found proceed with execution
2. If no valid config is found in the first step check $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli. If valid files are found proceed with execution
3. If no valid config is found inform user to run `init` and abort program execution

**2. Step:**
Add the parameter `--config` (overwriteable by environment variable `$CONFIG`) which will specify the third directory to look for the files.

When executed with the parameter or env var set the application behaves a little different:

_The program is executed with `init` command and $CONFIG set:_

Execute `init` process but write files to the directory specified in `$CONFIG`. It's the users task to make sure the program has write permissions to create the directory or create the necessary files inside the directory. 

_The program is executed with any other command and `$CONFIG` set:_

1. Look for keys and nodeFile.json in `$CONFIG`. If valid files are found proceed with execution
2. If no valid config is found look for keys and nodeFile.json in $HOME/.gladius-cli. If valid files are found proceed with execution
3. If no valid config is found in the first step check $NPM_CONFIG_PREFIX/lib/node_modules/gladius-cli. If valid files are found proceed with execution
4. If no valid config is found inform user to run `init` and abort program execution

**Comment by kleoken** [comment]
We are taking this into consideration for the next version. If you'd like to implement this yourself please do and then make a pull request

**Comment by sebastianhutter** [comment]
@Celo44, Of course, I can write some code and create a PR, but I would like to discuss this a little further. Configuration can be tricky ;-)

If the GitHub issues page is not the right way to discuss possible features and design questions should we create GitHub project?

**Comment by kleoken** [comment]
@sebastianhutter I've re-opened the issue to discuss further. I'm also checking out your previous PR right now.

**Comment by sebastianhutter** [comment]
thank you :-) I added some comments to #12 and I think this goes into a similar direction as #15
