### ISSUE TITLE
No way to view what a node is doing

### ISSUE THREAD

**Issue by jeholliday** [gladiusio/gladius-cli#59]
The `gladius status` command is extremely limited. It claims to be running, but it doesn't indicate what it's actually doing. This command should be updated to provide more useful status information. #

**Comment by code-merc** [comment]
Currently I think that's all that would really be useful in a CLI, however if you want to view more information about the services running (like logs) you can check the guardian for more information about the network gateway and the edge daemon. 

For quickly seeing logs you can go to http://localhost:7791/service/logs in your browser, you can also check out the full guardian API docs here: https://gladiusio.github.io/gladius-guardian-api-docs/
